# Generated by Django 4.0.2 on 2022-02-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_egn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default='No Name', max_length=40, null=True),
        ),
    ]
