# Generated by Django 4.0.2 on 2022-02-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software developer'), (2, 'QA Engineer'), (3, 'DevOps Specialist')], default=1),
            preserve_default=False,
        ),
    ]
